### ISSUE TITLE
Weird behavior in Chrome in the demo page

### ISSUE THREAD

**Issue by orck-adrouin** [yusukeshibata/react-pullrefresh#13]
Hello,

I found a weird behavior in the [demo](https://yusukeshibata.github.io/react-pullrefresh/) page when using Chrome/Firefox: if I drag & drop some text the pull to request action is triggered but now always.

This behavior is tricky to reproduce.  I included an animated gif to show you the weird behavior.

![pull-to-refresh-demo-chrome](https://cloud.githubusercontent.com/assets/16353378/25145472/4bcafcfa-243f-11e7-8cd0-60871b4aa262.gif)

**Comment by yusukeshibata** [comment]
This problem is probably solved with v1.5.8, check it please.

**Comment by orck-adrouin** [comment]
I'll wait until you reply on my new comment in issue #12
