### ISSUE TITLE
It is possible to controle the animation of the spinning icon?

### ISSUE THREAD

**Issue by orck-adrouin** [yusukeshibata/react-pullrefresh#15]
More specifically I would like the icon to disappears once the user release the the pull action.  I have my own loading icon and it looks a bit weird having both visible at the same time.

![image](https://cloud.githubusercontent.com/assets/16353378/25180866/9203a002-24dd-11e7-8890-2416bd0eee2a.png)

**Comment by flipace** [comment]
same issue here :) apart from that - this component is great!

**Comment by yusukeshibata** [comment]
Thanks issuing, I will implement setting custom ui for pulling and loading separately on #17.

**Comment by yusukeshibata** [comment]
@flipace @orck-adrouin 

I just supported custom render.
You can disable rendering on waiting state with `waitingComponent={false}`
```js
const renderWaitingComponent = (props) => {
  return <div style={{backgroundColor:'#00f', color:'#fff'}}>waiting</div>
}
const renderPullingComponent = (props, step) => {
  return <div style={{backgroundColor:'#f00', color:'#fff'}}>{step + '/' + props.max}</div>
}

<PullRefresh
  waitingComponent={false}
  pullingComponent={renderPullingComponent}
/>
```
