### ISSUE TITLE
Refresh is called twice

### ISSUE THREAD

**Issue by orck-adrouin** [yusukeshibata/react-pullrefresh#16]
Hello,

I just noticed when I "pull to refresh" my refresh method is called twice.

Demo:
![refresh-twice](https://cloud.githubusercontent.com/assets/16353378/25182254/0656937a-24e2-11e7-9d1a-fea25a133c80.gif)

You can see 2 console messages instead of the expected one.  This is an issue for me because I'm doing a network call to refresh my page and I do not want to call it twice.  I can probably workaround the issue with a horrible hack but I would like to avoid that.

Relevant code:
```
  // this is my onRefresh method
  handleRefresh(next) {
    console.warn("handleRefresh")
    next(); 
  }
```

This is how I declared the component:
```
 <PullRefresh zIndex={10000} size={40} max={100} onRefresh={this.handleRefresh}>
            <div style={{ overflow: 'auto', height: '100%', width: '100%' }}>
              There are many variations of passages of Lorem Ipsum available [...]
            </div>
          </PullRefresh>
```

**Comment by yusukeshibata** [comment]
Thanks reporting, fixed with v1.5.9
