### ISSUE TITLE
Minified development version used in production builds

### ISSUE THREAD

**Issue by westbyb** [yusukeshibata/react-pullrefresh#18]
When I go to build my app for production, I get the following error:

`Warning: It looks like you're using a minified copy of the development build of React. When deploying React apps to production, make sure to use the production build which skips development warnings and is faster. See https://fb.me/react-minification for more details.`

Removing react-pullrefresh fixes the issue, and from what I can tell from the minified code, the process.env.NODE_ENV is undefined when it checks.

Following the guide provided here: https://facebook.github.io/react/docs/optimizing-performance.html#use-the-production-build

**Comment by yusukeshibata** [comment]
Thanks reporting, fix with v1.6.5.

**Comment by westbyb** [comment]
Builds correctly now! Thanks!
