### ISSUE TITLE
Strange behavior in the demo page

### ISSUE THREAD

**Issue by orck-adrouin** [yusukeshibata/react-pullrefresh#20]
Is the [demo page](https://yusukeshibata.github.io/react-pullrefresh/) using the latest version?  There's a strange behavior on this page: the loading icon is showing itself without having to click on the page.  Simply moving the mouse is enough to display the loading icon. Clicking on the page seems to fix the problem.

Screen capture below to show the issue (using Chrome), note that I am only moving the move and I never clicked on the page since loading it.
![ptr](https://user-images.githubusercontent.com/16353378/29622446-749eccea-87f1-11e7-8bf8-e63e4d5fcf29.gif)

**Comment by yusukeshibata** [comment]
I think its fixed.
