### ISSUE TITLE
Display different component when refresh is complete

### ISSUE THREAD

**Issue by orck-adrouin** [yusukeshibata/react-pullrefresh#21]
Hi,

is it possible to display a different component once `onRefresh` has been called?  Currently the "flow" of `react-pullrefresh` is as follow:

1. User starts pulling
2. `react-pullrefresh` is displayed and uses the `pullingComponent` property to know what to display (an arrow in a circle)
3. User stops pulling
4. `react-pullrefresh` uses the `waitingComponent` property to know what to display (circular loading)
5. `onRefresh` is called and the callback is resolved
6. `react-pullrefresh` uses the `pullingComponent` property to know what to display (arrow in a circle) and starts hiding the component by moving it to the top

I would like to display a different component in step 6 to let the user know that the refresh has completed.

**Comment by yusukeshibata** [comment]
@orck-adrouin Hi, thanks for requesting.
Supported `pulledComponent` prop with v1.6.6

https://github.com/yusukeshibata/react-pullrefresh/commit/f5f52ad536e65f05427a53a6694e4ffdd53d6f47
