### ISSUE TITLE
Refresh component not centered

### ISSUE THREAD

**Issue by orck-adrouin** [yusukeshibata/react-pullrefresh#22]
Hello,

The refresh component is not centered on the page.  I didn't check the waiting component but I assume it has the same issue.

![image](https://user-images.githubusercontent.com/16353378/29784554-60b19140-8bf2-11e7-8781-0cf9b25f06ae.png)

**Comment by yusukeshibata** [comment]
@orck-adrouin Hi, I tested on latest chrome, firefox, safari, internet-explorer, edge, but I couldn't reproduced this behaivour.
Is it occuring now?

**Comment by orck-adrouin** [comment]
I upgraded to the latest version and I could still see this behavior.  I looked at my code to see what is different than the demo page and I saw that I am using a custom `pullingComponent` so I removed it and the problem was not present when using the default `pullingComponent`.  I looked at the code of `main.js` and I saw that the default `pullingComponent` has a `translateX` transformation.  

I added something similar (marginLeft: -50%) and I was able to fix the issue with my custom component.  

I think we can close this issue but I also think this transformation should be added to the `README` file.  What do you think?

**Comment by yusukeshibata** [comment]
Hi @orck-adrouin ,
I changed layout behavior for the component from v1.6.8.
Component will be layout on the center of 100% width container.
