### ISSUE TITLE
Unable to give focus to input[type=text] elements

### ISSUE THREAD

**Issue by orck-adrouin** [yusukeshibata/react-pullrefresh#25]
When using `react-pullrefresh` in a page containing a textbox (`<input type="text" />`), the focus is not given to the textbox when clicking on it.

How to reproduce: add a textbox to the demo page and try to give it focus by clicking it.

Expected result: textbox receive the focus and user can modify its value

Obtained result: nothing is happening

**Comment by yusukeshibata** [comment]
Fixed on v1.6.9
