### ISSUE TITLE
How to change color of refresh circle

### ISSUE THREAD

**Issue by vkpraveen** [yusukeshibata/react-pullrefresh#9]
Hi 

Right now there is no props exposed to update default color of refresh circle.

Can you please provide this option?

/src/index.js:

`<svg
              style={{
                margin: (size - 30) / 2,
                opacity: step / max,
                transform: transform([
                  { rotate: `${step / max * 360}deg` }
                ]),
                ...(loading && { animation: 'rotating 1.4s ease-in-out infinite' })
              }}
              width={30}
              height={30}
              viewBox='0 0 30 30'
            >
              { !pulled &&
                  <path
                    **fill='#000'**
                    d='M13.3,15L7.1,8.9L0.9,15'
                  />
              }
              <circle
                style={{
                  transformOrigin: 'center',
                  ...(loading && { animation: 'dash 1.4s ease-in-out infinite' })
                }}
                **stroke='#000'**
                strokeDasharray={Math.PI * 8}
                strokeDashoffset={0}
                fill='none'
                strokeWidth={2}
                cx={15}
                cy={15}
                r={8}
              />
            </svg>`

**Comment by yusukeshibata** [comment]
Hi

Supported with v1.4.0

```js
import Pull from 'react-pullrefresh'
<Pull color='#f00' />
```

**Comment by vkpraveen** [comment]
Still it is not reflecting.....Can you please have a look again.

Inside your repo/test it is working as expected but when I add through npm module into my project it is not reflecting.

**Comment by yusukeshibata** [comment]
Oh, sorry fixed with 1.4.1.

**Comment by vkpraveen** [comment]
Perfect!! it is working as expected.
